teste[{COD_MENU, int(11), NO, PRI, }] 
[{DSC_MENU, varchar(50), NO, , }] 
[{COD_MENU_PAI, int(11), NO, , }] 
[{NME_CONTROLLER, varchar(100), NO, , }] 
[{NME_METHOD, varchar(100), NO, , }] 
[{DSC_ATIVO, enum('S','N'), NO, , }] 
[{IND_ATALHO, enum('S','N'), NO, , }] 
[{DSC_CAMINHO_IMAGEM, varchar(100), NO, , }] 
